services:
  - type: web
    name: rollari
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn rollari.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rollari.settings.production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
