# Generated by Django 5.1.5 on 2026-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp Number')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('adults', models.PositiveIntegerField(default=2, verbose_name='Number of Adults')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Number of Children')),
                ('experience', models.CharField(choices=[('deep_sea', 'Deep Sea Big Game Fishing'), ('night_fishing', 'Traditional Night Fishing'), ('sport_trolling', 'Sport Trolling'), ('whale_shark', 'Whale Shark Safari'), ('manta_ray', 'Manta Ray Encounter'), ('dolphin_cruise', 'Dolphin Sunset Cruise'), ('sandbank', 'Sandbank Picnic'), ('island_hopping', 'Island Hopping Adventure'), ('snorkeling', 'Snorkeling Expedition'), ('ultimate', 'Ultimate Ocean Expedition (Signature)'), ('custom', 'Custom / Multiple Experiences')], max_length=50, verbose_name='Experience')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('flexible_dates', models.BooleanField(default=False, verbose_name='Flexible with Dates')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='How did you hear about us?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
